feat(Request options): Request options for Requesting class #21
brawlup/brawlup.js pull request #23
Opened 2021-09-05 10:42 UTC by leecheeyong

please refer to #21

2021-09-05 15:03 UTC, alputv requested changes
Please revert the jsdoc and Client changes.

2021-09-06 00:44 UTC, leecheeyong commented
aight, done

2021-09-16 12:49 UTC, leecheeyong commented
> 
> 
> Please revert the jsdoc and Client changes.

done

2021-09-16 14:23 UTC, alputv approved these changes

2021-09-16 14:23 UTC, merged